version: '2'
services:
    mozhotelsbooking-app:
        image: mozhotelsbooking
        external_links:
            - mozhotelsbooking-postgresql:postgresql
            - mozhotelsbooking-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mozhotelsbooking
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    mozhotelsbooking-postgresql:
        extends:
            file: postgresql.yml
            service: mozhotelsbooking-postgresql
    mozhotelsbooking-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mozhotelsbooking-elasticsearch
